version: '3'
services:
  node:
    build: .
    restart: always
    environment:
      NODE_ENV: development
      PORT: 80
    ports:
      - '80:3000'
    volumes:
      - .:/usr/src/node
      - /usr/src/node/node_modules
    links:
      - mongo:mongo
  mongo:
    build: ./mongo
    restart: always
    ports:
      - '27017:27017'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    links:
      - mongo:mongo
